### PR TITLE
Fix ffwd merged

### PR DESCRIPTION
**Pull request by albaintor**

### CODE REVIEW

**Comment by albaintor** [comment]
Hi, all done there (merge) and also I changed a little the behaviour of ffwd and rewind companion :
- If press ffwd companion while there is a rewind_begin => stop the rewind and launch the ffwd_begin. 
- Same for the opposite (if pressing rewind while ffwd is running, we stop ffwd first)

**Review by zehnm — COMMENTED** [review]
Looks good to me!
Just one question: is `await self.stop_fast_forward_rewind()` also required in the `fast_forward()` and `rewind()` functions, as you added them in `next`, `previous`, `skip_forward`, and `skip_backward`?

**Comment by albaintor** [comment]
You're right I'll add to them

**Comment by albaintor** [comment]
Done

**Review by zehnm — APPROVED** [review]
Thanks, this gives a few more options.

The app specific FF / RW behaviour on Apple TV is indeed an absolut mess. Just tried a few apps, and it was different everywhere :-(
- ATV+ is mixed: it works with the new commands, old FF / RW sometimes work, sometimes not
- Plex: new FF / RW begin commands don’t work
- Red Bull TV: only new skip commands work
- Play Suisse: only works with the old FF / RW, where it’s only skipping.
- Play SRF: works with the old FF / RW (this time true forward & rewind, no skipping), plus the new FF / RW begin commands.

Quite depressing, but nothing we can do.

**Comment by albaintor** [comment]
Yes agreed, as a result I mapped FF/RW begin commands to the physical buttons, and I added old FF/RW to the screen.
FF/RW begin seem to work with most apps but not all

Maybe the upcoming touch gestures could help in the future (I am still waiting for the admin to approve the PR)

**Pull request merged**
