### PR TITLE
Added 2 simple commands for skip forward and backward

### PR DESCRIPTION
**Pull request by albaintor**
Hi,

I added those 2 simple commands that were already defined in the integration library but unmapped. It will address some apps having issues with fast forward / rewind commands (disney+)

### CODE REVIEW

**Review by zehnm — CHANGES_REQUESTED** [review]
Thanks the enhancement! Playback control really is a hit-or-miss with some apps.
I've quickly verified it and it looks good to me.
Please fix the pylint issues, then I'll merge it.

**Comment by albaintor** [comment]
It should be okay now ! Keep up the good work !

**Review by zehnm — CHANGES_REQUESTED** [review]
Sorry to bother you again, linting check is still failing.

You can easily check & format it locally: https://github.com/unfoldedcircle/integration-appletv/blob/main/docs/code_guidelines.md#verify

**Comment by albaintor** [comment]
Hi Markus,

No problem, code formating was okay (with black) but I forgot to apply "sort imports" tasks.
Done now

Cheers,
Damien

De : Markus Zehnder ***@***.***>
Envoyé : lundi 10 juin 2024 18:11
À : unfoldedcircle/integration-appletv ***@***.***>
Cc : albaintor ***@***.***>; Author ***@***.***>
Objet : Re: [unfoldedcircle/integration-appletv] Added 2 simple commands for skip forward and backward (PR #19)


@zehnm requested changes on this pull request.

Sorry to bother you again, linting check is still failing.

You can easily check & format it locally: https://github.com/unfoldedcircle/integration-appletv/blob/main/docs/code_guidelines.md#verify

-

**Review by zehnm — CHANGES_REQUESTED** [review]
One unused-import left

**Comment by albaintor** [comment]
Sorry either I was blind but I didn't any warning after running checks... should be fixed now...hopefully

**Review by zehnm — CHANGES_REQUESTED** [review]
One last `python -m isort intg-appletv/.` and it should be good :-)

**Comment by albaintor** [comment]
OMG, I am so bad... sorry I want to go fast and this is worse

**Review by zehnm — APPROVED** [review]
Thanks! All good now.

**Pull request merged**
